### ISSUE TITLE
ValueConverter - using object as parameter throws error

### ISSUE THREAD

**Issue by markpritchett** [aurelia/templating-binding#10]
I am trying to create a TruncateValueConverter.  This is what I have so far:

<pre>
<code>
export class TruncateValueConverter {
    toView(value, opts) {
        console.log(opts);
        // TODO: Implement value converter
    }    
}
</code>
</pre>

The html is:

<pre>
<code>
${contact.lastName | truncate:{ limit: 10 } } 
</code>
</pre>

I get the following error "Potentially unhandled rejection [2] Error: Parser Error: Missing expected } at the end of the expression [contact.lastName | truncate:{ limit: 10 ]"

**Comment by jdanyow** [comment]
@EisenbergEffect I tried a few different parsing algorithms to address this with varying success:
http://jsperf.com/aurelia-interpolation

Each option in the js-perf produces the correct result but they're not nearly as fast as the baseline.

I'd like to submit this to the gitter chat to see if someone can come up with something better.  Before I did that I wanted to make sure what I'm doing is in sync with what you were thinking for this issue.

**Comment by EisenbergEffect** [comment]
You are on the right track. We just may have to go with the mark and allocate method. Can you add to these implementations the ability to escape the interpolation? So anything starting with `\${` would not be matched.

From a performance perspective, I'm wondering if we could reduce the array work in this implementation by keeping start and end index local variables and as an interpolation is matched...just processing the final version right then.

**Comment by Alxandr** [comment]
So, I made a contribution to the jsperf (curse you @jdanyow) at http://jsperf.com/aurelia-interpolation/2.

It's a simple dsl that handles escaping, and does not construct objects or populates arrays, but rather work in a generator like fashion (it's not an ES6 itterator) where it yields values one by one through a callback. In chrome, it performs more or less the same as all the other ways added by @jdanyow, which is aproximately 70% slower than the baseline (`string.split(regex)` must be friggin fast on chrome). In IE11, the DSL performs ~2.5 times faster than the baseline. I've yet to get results from firefox and safari as I don't have them.

Also, there are probably more optimizations that can be done. I don't know how to optimize stuff like this. It might for instance be faster to just search for `$` instead of `${`, and then check the next char, or something like that.

**Comment by jdanyow** [comment]
@EisenbergEffect @Alxandr :

I put together **[another jsperf](http://jsperf.com/aurelia-interpolation-allocate-strings)** with a more precise definition of what it's comparing.:  

> This is a comparison of algorthms that produce the same kind of output as the original implementation: an array of strings whose even members are text literals and whose odd members are binding expressions.

My goal here was to do an apples to apples comparison with the original algorithm so that the comparison was meaningful.  

My reasoning was the interpolation code ultimately needs to substring out each part of the original string to send to the parser or to build the interpolation result.  We may be able to get away with not allocating an array to hold all the parts and we may be able to update the parser to accept a string+startposition+endposition but that was not in the scope of this particular benchmarking exercise.

---

For each algorithm there are two tests:  one against a set of short strings and another against a big block of text interspersed with interpolation bindings.  I'm not sure how common the big block of text scenario will be but I included it for completeness.

A couple algorithms stood out:
- **parseSequential**:  this one iterates over each character.  It out-performs the original in chrome when the strings being parsed are short.  Also works well in other browsers.
- **parseSequential2**:  this one works a lot like parseSequential except that it uses a regex to "fast-forward" to interesting characters in the string `\ { } $ " '`.  It out-performs parseSequential when the string being processed is large.  In Internet Explorer it out-performs parseSequential across the board.

---

My current plan is to create a pull request with tests for all the different cases (escaping, object literals, string literals, etc) with the fix using the algortithm from parseSequential or parseSequential2 (or even selecting the algorithm dynamically based on the input length if you think that's a better plan).

If we decide to refactor further the algorithms can easily be updated to yield the {start,end,expressionType} if that's ends up being more performant with the downstream changes to the parser or the interpolation result building.

This would address the defects and enhancements.  With the tests in place it will be easier for contributers to tweak and refactor the algos.

Thoughts?

**Comment by jdanyow** [comment]
thanks to @Alxandr for showing me how to create a WIP pull request- any feedback welcome

**Comment by Alxandr** [comment]
I created a spec issue for this, because as it stands there are some things that need to be made sure off. For instance, in both of our implementations, it turns out that if you have a value with a escaped interpolation expression, and no actual interpolation expressions, the backslash doesn't get removed.

I'll try to make a test-suite for all of the samples tomorrow. Please review at #18.
