### ISSUE TITLE
Spec: Interpolation parser

### ISSUE THREAD

**Issue by Alxandr** [aurelia/templating-binding#18]
I would just like to spec this out a bit, because as far as I know currently both PRs on this repo for interpolation parsers has a few (common) problems. So I'd like to get here a list of input => output pairs of what's the expected result. Before I start though, I'd like to say that if I've missed anything, please do comment scenarios you might have, and I'll add them to the list.

For the purpose of having some data, I'm going to define a view model like this:

``` javascript
export class ViewModel {
  constructor() {
    this.name = 'test';
  }

  getName() {
    return this.name;
  }
}
```

I'm also going to pretend there is a value converter named `upper`, that uppercases everything,
and another one named `json` that appends it's parameter (in JSON form) to the original value.
## Simple interpolation

The basic interpolation (that also works today) are:
### Single variable interpolation

``` html
<!-- before -->
<div>${name}</div>

<!-- after -->
<div>test</div>
```
### Constant value interpolation

``` html
<!-- before -->
<div>${'name'}</div>

<!-- after -->
<div>name</div>
```
### Function call expression interpolation

``` html
<!-- before -->
<div>${getName()}</div>

<!-- after -->
<div>test</div>
```
### Tenary expression interpolation

``` html
<!-- before -->
<div>${true ? 'true' : 'false'}</div>

<!-- after -->
<div>true</div>
```
### Value converter interpolation

``` html
<!-- before -->
<div>${name | upper}</div>

<!-- after -->
<div>TEST</div>
```
### Value converter with parameter interpolation

``` html
<!-- before -->
<div>${name | json:'foo'}</div>

<!-- after -->
<div>TEST"foo"</div>
```
### Value converter with object parameter interpolation

``` html
<!-- before -->
<div>${name | upper:{foo: 'bar'}}</div>

<!-- after -->
<div>TEST{"foo":"bar"}</div>
```
### Value converter with array parameter interpolation

``` html
<!-- before -->
<div>${name | upper:['foo', 'bar']}</div>

<!-- after -->
<div>TEST["foo","bar"]</div>
```
### Escaped interpolation

``` html
<!-- before -->
<div>\${name}</div>

<!-- after -->
<div>${name}</div>
```
### Interpolation with backslash in front

``` html
<!-- before -->
<div>\\${name}</div>

<!-- after -->
<div>\\test</div>
```
### Interpolation with string with escaped quotes

``` html
<!-- before -->
<div>${'name\''}</div>

<!-- after -->
<div>name'</div>
```
### Interpolation with string with escaped slashes

``` html
<!-- before -->
<div>${'name\\'}</div>

<!-- after -->
<div>name\</div>
```
### Interpolation with string with object literals inside them

``` html
<!-- before -->
<div>${'{}'}</div>

<!-- after -->
<div>{}</div>
```
### Interpolation with string with partial object literal inside them

<small>This one seems obvious what should happen, but it's been
one of the hard one to make sure works in the parsers, thus adding.</small>

``` html
<!-- before -->
<div>${'{'}</div>

<!-- after -->
<div>{</div>
```
## Questions

There are a few examples that I'm unsure how should be handles, and that I think should be discussed. These are as following:
### Partial interpolation

``` html
<div>${name</div>
```

What should happen here? I see tree options:
1. Throw an error. Interpolation was not closed. To remove the error, either close the interpolation (as was probably intended 90% of the time), or escape it with `\`. I am personally in favor of this, as I think it will solve a lot of issues ahead of time.
2. Output as `<div>${name</div>`, but show a warning. Require escaping to remove warning.
3. Output as `<div>${name</div>` and do not warn.

In case point 3 is selected, it can also be discussed how the following should be printed: `<div>\${name</div>`. Should the backslash be kept? Or not?
### Partial string in interpolation

``` html
<div>${"test</div>
```

The options are the same as the previous one. Here at least I think we should throw,
unless it's escaped.

**Comment by BalassaMarton** [comment]
I don't know if there will be any 'out of the box' converters (or if this comment even belongs here), but I think converters should always take zero or one parameter, and it should be an object when there are more than one argument for the conversion. In many scenarios, template authors / UI designers work separately from coders, and even a converter with 2 parameters can obfuscate the template. Consider, for example, the below snippet, taken from the [latest blog entry](http://eisenbergeffect.bluespire.com/binding-with-value-converters-in-aurelia/#):

``` html
<tr repeat.for="repo of repos | sort:column.value:direction.value | take:10">
```

There are two problems with this syntax. (1) The colons split the conversion declaration into three parts, and the reader could think that the parts are on the same syntactic level. At best, it produces poor readability. (2) The template author needs to know the order of parameters, but that's not even trivial for a coder (that's why we push Ctrl+Shift+Space in VS like a monkey), let alone for a designer. So, for the above example, the new declaration would look something like this:

``` html
<tr repeat.for="repo of repos | sort: {key: column.value, direction: direction.value} | take: 10">
```

Note that this change does not require any modification in the parser, it's a convention that should be followed to minimize confusion. One additional benefit of this convention is that a converter can define a default value for any parameter, and the template author can omit any parameter, regardless of order.

**Comment by Alxandr** [comment]
Yeah, this is probably not the right issue to discuss this. If you want this added as a constraint (if it isn't already), you should add a separate issue.

**Comment by BalassaMarton** [comment]
OK, I'll move it.

**Comment by EisenbergEffect** [comment]
I think this is tracked in the tests now.

**Comment by Alxandr** [comment]
Actually, it's not. We really need to test this at a higher level than the interpolation parser. Because, if you take a look at my implementation of the interpolation parser, it passes all of these tests, but if you use it in practice, it fails several of them. There needs to be tests of "here's html and a vm, now render it".

**Comment by kplatter** [comment]
These were really good examples, can someone add it to the docs?
