### ISSUE TITLE
Support for `default property` binding

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/templating-binding#56]
Having a _custom attribute_ with multiple `@bindable` like

```
export class Foo {
  @bindable callback1 = () = {};
  @bindable callback2 = () = {};
}
<div foo="callback1.call:$parent.onCallback1($event);"></div>
```

it would be really nice to be able to set a `default property` so you could do

```
<div foo="$parent.onCallback1($event)"></div>
```

which make sense if `callback1`is the `default property` for the _custom attribute_.

Let me know if you need more input.

**Comment by stoffeastrom** [comment]
@EisenbergEffect is this implemented? Don't remember if this got it or not :)

**Comment by EisenbergEffect** [comment]
Has not been implemented yet.

**Comment by stoffeastrom** [comment]
What about adding a third parameter in the _custom attribute_ decorator

```
export function customAttribute(name: string, defaultBindingMode?: number, defaultAttributeName: string): any {
  validateBehaviorName(name, 'custom attribute');
  return function(target) {
    let r = metadata.getOrCreateOwn(metadata.resource, HtmlBehaviorResource, target);
    r.attributeName = name;
    r.attributeDefaultBindingMode = defaultBindingMode;
    r.defaultAttributeName = defaultAttributeName;
  };
}
```

and in the `syntax-interpreter.js`

```
options(resources, element, info, existingInstruction) {
    let instruction = existingInstruction || BehaviorInstruction.attribute(info.attrName);
    let attrValue = info.attrValue;
    let language = this.language;
    let name = null;
    let target = '';
    let current;
    let i;
    let ii;

    for (i = 0, ii = attrValue.length; i < ii; ++i) {
      current = attrValue[i];

      if (current === ';') {
```

###### No name try the `defaultAttributeName`

```
        name = name || resources.attributes[info.attrName].defaultAttributeName;
        info = language.inspectAttribute(resources, name, target.trim());
        language.createAttributeInstruction(resources, element, info, instruction);

        if (!instruction.attributes[info.attrName]) {
          instruction.attributes[info.attrName] = info.attrValue;
        }

        target = '';
        name = null;
      } else if (current === ':' && name === null) {
        name = target.trim();
        target = '';
      } else {
        target += current;
      }
    }

    if (name !== null) {
      info = language.inspectAttribute(resources, name, target.trim());
      language.createAttributeInstruction(resources, element, info, instruction);

      if (!instruction.attributes[info.attrName]) {
        instruction.attributes[info.attrName] = info.attrValue;
      }
    }

    return instruction;
  }
```

`custom attribute` file

```
@customAttribute( 'foo', null, 'callback1.call' )
export class Foo {
  @bindable callback1 = () = {};
  @bindable callback2 = () = {};
}
```

``` markup
<div foo="onDefaultCallback()"></div>
```

Oh and right know if you type it wrong in the markup it will fail on

```
var parts = attrName.split('.');
```

in `inspectAttribute` since it is null.

Thoughts???

**Comment by stoffeastrom** [comment]
It might even by cleaner to do

```
<div foo.call="onDefaultCallback()"></div>
```

ping @EisenbergEffect

**Comment by piwnik** [comment]
In my opinion it should be:

<pre>
&lt;div foo=&quot;onCallback1&quot;&gt;&lt;/div&gt;
</pre>

where 
if no properties defined in html, then value shall be assigned to default bindable property, so in this case

<pre>
&lt;div foo=&quot;onCallback1&quot;&gt;&lt;/div&gt;
</pre>

shall be equal to

<pre>
&lt;div foo=&quot;callback1:onCallback1&quot;&gt;&lt;/div&gt;
</pre>

**Update** 

<pre>
foo.call
</pre>

in

<pre>
&lt;div foo.call=&quot;onDefaultCallback()&quot;&gt;&lt;/div&gt;
</pre>

isn't very good, because sometimes is useful assign simple text, not function. In such case **"{attributeName}.call="** will be not so clear as simple **"{attributeName}="**

**Comment by stoffeastrom** [comment]
Well, you would add that if it's a `@bindable function` otherwise it doesn't make sense.

@EisenbergEffect what's your take on this?

**Comment by EisenbergEffect** [comment]
I'd like to have a feature like this. We need to wait to implement some other higher priority things right now though.

**Comment by stoffeastrom** [comment]
Of course! I might find time to do a PR if you think the above makes sense....

**Comment by jdanyow** [comment]
@EisenbergEffect / @stoffeastrom did you decide on a preferred API for telling the templating engine that a particular `@bindable` property in a custom attribute's set of bindable properties is the "default" property? I'm hoping to revive this issue to help streamline some validation stuff.

**Comment by EisenbergEffect** [comment]
I don't think we settled on anything in particular. If you want to work on this, make a proposal and work though that to get an implementation. If you're going to work on bindables, there are a couple of other things we might want to do together, such as typed bindables and bindables that are boolean attributes, etc.

**Comment by jdanyow** [comment]
There's a feature in validation @dkent600 is looking for that this is blocking, if there's something we can do for this without shooting ourselves in the other bindable issues, it would be awesome, was hoping to recruit @dkent600 to contribute both this and the validation feature.

**Comment by EisenbergEffect** [comment]
Let's just handle this one scenario for now then. Just work up a short proposal for the api.

**Comment by jdanyow** [comment]
Here's an initial pass at this. @EisenbergEffect, @stoffeastrom, @dkent600 let me know what you think:

## Use Case

We have a [`validation-errors`](https://github.com/aurelia/validation/blob/master/src/validation-errors-custom-attribute.ts) custom attribute that will dump errors related to the DOM node it appears on into the array property it's bound to:

```html
<form validation-errors.bind="orderFormErrors">
  ... inputs, etc ...
</form>
```

The custom attribute has a dependency on a validation controller instance, which is supplied to it's constructor by the container. We'd like to allow developers to provide the controller instance via data-binding to improve flexibility.

Assuming we add the following bindable properties to our custom attribute:
```js
export class ValidationErrorsCustomAttribute {
  @bindable value;
  @bindable controller;
}
```

The binding will need to change to:

```html
<form validation-errors="value.bind: orderFormErrors">
  ...
</form>
<form validation-errors="value.bind: orderFormErrors; controller.bind: orderController">
  ...
</form>
```
This is not ideal because current users of the custom attribute will be forced to use the ["options" binding syntax](http://aurelia.io/hub.html#/doc/article/aurelia/templating/latest/templating-custom-attributes/5) even though they do not need to data-bind the controller property. The options syntax is slightly more verbose, used infrequently and can be hard to remember. It would be great if there was a way for the templating system to know that a particular bindable property is the custom attribute's "default" binding target. When the "options" attribute binding syntax is not used, the templating system could feed the attribute value into the default property.

## Desired Capability

```js
export class ValidationErrorsCustomAttribute {
  @bindable value;  // somehow indicate to the templating system that this is the default binding target
  @bindable controller;
}
```
```html
<!-- Preserve existing "explicit" property binding: -->
<form validation-errors="value: orderFormErrors, controller: orderController">
  ... inputs, etc ...
</form>
<!-- Desired "default" property binding, with a binding command: -->
<form validation-errors.bind="orderFormErrors">
  ... inputs, etc ...
</form>
<!-- Desired "default" property binding, without a binding command: -->
<form validation-errors="not a binding expression... just a string here">
  ... inputs, etc ...
</form>
```
*note: the last example doesn't make sense for the validation-errors custom attribute but needs to be considered for this enhancement*

## Design

There are quite a few ways we could do this. Here are a couple:

1. Aurelia favors convention over configuration. There should be a convention for this. Maybe any bindable property named `value` should automatically become the default.
2. Developers should be able to override any convention. Perhaps the `bindable` custom attribute and in turn the `BindableProperty` class should accept a new configuration attribute: `default: boolean`:
    ```js
    @bindable({ default: true }) foo;
    @bindable bar;
    ```

## Implementation

The `HtmlBehavior` class will need an O(1) "default property" lookup, perhaps via a new nullable property.

Areas that may need changes:
* https://github.com/aurelia/templating/blob/1.1.4/src/html-behavior.js#L132
* https://github.com/aurelia/templating/blob/1.1.4/src/view-compiler.js#L353
* https://github.com/aurelia/templating/blob/1.1.4/src/view-compiler.js#L223
* others?

**Comment by EisenbergEffect** [comment]
I think using the property named `value` would be a reasonable convention. However, the name `value` isn't typically what you want when there are multiple properties. You usually want something more distinguishable. So, it may be that we need to use the bindable setting. I'm not sure we should just call it `default` though.

**Comment by EisenbergEffect** [comment]
I think you've identified the main areas that will need changes. On a related note, there's an opportunity to refactor some shared code between compileElement and compileSurrogate.

**Comment by stoffeastrom** [comment]
Another alternative could be `singleValueDefault`?

**Comment by dkent600** [comment]
`defaultBindable` ?

**Comment by dkent600** [comment]
What would happen in the case that more than one bindable properties have `defaultBindable` (or whatever we call it) set to true?

**Comment by jdanyow** [comment]
@dkent600 re: *what should happen when two or more props are configured to be default*
let's throw an error in this case

---

@EisenbergEffect good call: `default` is not a specific enough name for the bindable config option given all the other stuff we may do with `@bindable` in the future. Here's a few options in addition to the ones @stoffeastrom  and @dkent600 mentioned:
* `attributeDefault`
* `defaultTarget`
* `defaultBindingTarget`
* `defaultProperty`

The other thought I had was to drop "default" from all the terminology/naming in this enhancement and replace it with "primary". Then maybe we'd name the config option:
* `primary`
* `primaryProperty`

**Comment by dkent600** [comment]
I will get started on this today

**Comment by dkent600** [comment]
@jdanyow What is your preferred method of communication, by which I can pose questions to you?

**Comment by dkent600** [comment]
@jdanyow @EisenbergEffect

Is there another alternative here,  rather than:

`@bindable({ defaultBindable: true }) foo;`

add a parameter to `customAttribute`:

`@customAttribute("myAttributeName", bindingMode.oneWay, "foo")`

(I note that the second parameter (bindingMode) doesn't seem to be documented, that I can find, but unless I'm misunderstanding the code (and I **am** very new to it), it _does_ appear to exist.  Maybe it is not meant to be publicly-exposed, though it does seem like it could be useful when the custom attribute has no defined bindable property.)

**Comment by jdanyow** [comment]
@dkent600 you can hit me up on gitter with any questions: https://gitter.im/jdanyow

The second "binding mode" arg on the custom attribute decorator is helpful in situations where you've created something like `<input number-value.bind="height">` that should be a two-way binding by default.

**Comment by dkent600** [comment]
@jdanyow Any thoughts about doing this by adding a parameter to the `customAttribute` decorator? (in case you read over that suggestion)

**Comment by jdanyow** [comment]
It's an option- there's a couple things about it that make me prefer putting the flag on the bindable config:

1. Supplying the property name as a string is a little awkward, could be more prone to issues with refactoring, misspelling than the alternative.
2. Too many args in the `customAttribute` decorator. For API aesthetics we'd probably need to overload the decorator to accept a single config object parameter (like bindable) to enable users to specify one thing (name/binding mode/default prop) without needing to specify them all.

**Comment by EisenbergEffect** [comment]
I agree, let's keep this setting close to the actual bindable.

**Comment by stoffeastrom** [comment]
I just tried this but I can't get it right. Made a simple [gist](https://gist.run/?id=eff66c242a27f2ed97c2eecfbca89dff) to show the problem. It doesn't seem to work on functions?

**Comment by dkent600** [comment]
@stoffeastrom  I'm investigating

**Comment by dkent600** [comment]
@stoffeastrom  The gist you are using is pulling in old code that does not contain this feature.

@jdanyow

**Comment by stoffeastrom** [comment]
@dkent600 Oh, sorry about that but It doesn't work on the latest locally. I will see if I can get a newer gist running

**Comment by stoffeastrom** [comment]
@dkent600 @jdanyow I have updated the [gist](https://gist.run/?id=eff66c242a27f2ed97c2eecfbca89dff) and now it seems to work. Pretty cool I managed to get typescript transpiling working :)

It might be that I don't have the latest locally :man_facepalming: I will check

**Comment by stoffeastrom** [comment]
Jeeeesus sorry, I didn't have the latest guys. Works like a charm.

However we did get a [Aurelia Gist TypeScript](https://gist.run/?id=154a40fea5aa02c72a119c4658e1f1cf) 💥

**Comment by dkent600** [comment]
stoffeastrom Awesome gist!

Except that it's getting a 404 error:  " https://unpkg.com/aurelia-templating-resources/dist/amd/compose.js"

**Comment by stoffeastrom** [comment]
Hmm weird works on my machine =)

**Comment by dkent600** [comment]
OK, I refreshed and it worked ok.  Sweet!
