### ISSUE TITLE
should be possible for a view to not be unbound when deactivated

### ISSUE THREAD

**Issue by dkent600** [aurelia/templating-binding#95]
I find, even when assigning the decorator @singleton(false) to the view-model, that while the view-model does then persist as a singleton across activation/deactivation, the bindings and components, etc do not. 

(I assume this is because they are stored in a container that is disposed on deactivation.)

The result is that upon every deactivation/activation of a view with a singleton view-model, the view is un-bound and then re-bound. 

Is it possible to cause the bindings to persist across view deactivation/activation?

Durandal has this functionality.

As it stands, switching between views loses potentially a lot of visual state which can be quite a problem for the application user.  I think it is asking a lot of the developer to manually cache every little bit of UI state that is important on every view.

**Comment by EisenbergEffect** [comment]
I'm closing this since it's tracked elsewhere as a feature request. You can also implement your own router-view in the mean time to cache view instances. We are planning to address this in a future release. Regarding Durandal, the implementation there was severely problematic which is why we haven't done it in Aurelia yet. It's easy to do in an application specific way but it takes careful design to come up with a general purpose way of handling this.
